### ISSUE TITLE
ec2_find_ami depricated

### ISSUE THREAD

**Issue by kkorada** [majordomusio/ansible-aws-cluster-openshift#2]
**ec2_ami_find** will be depricated soon, (> 2.9)

Please change below ones at file **ansible-aws-cluster-openshift/roles/build_base_ami/tasks/provision-instance.yml**:
```
- name: Find AMI
  ec2_ami_find:
     image_id: "{{ image_id }}"
     region: "{{ region }}"
  register: "ami_find"
```
**to**

```
- name: Find AMI
  ec2_ami_facts:
     image_ids: "{{ image_id }}"
     region: "{{ region }}"
  register: "ami_find"
```
